// agent-rover - A multi-platform TypeScript test driver for GUI applications
// Copyright (c) Kouji Matsui. (@kekyo@mi.kekyo.net)
// Under MIT.
// https://github.com/kekyo/agent-rover

#ifndef AGENT_ROVER_WINDOWS_AGENT_AUTH_H
#define AGENT_ROVER_WINDOWS_AGENT_AUTH_H

#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

namespace agent_rover {

/** Random byte count used to generate one auth token. */
constexpr size_t kAuthTokenRandomBytes = 32;

/** Base64url text length produced for one generated auth token. */
constexpr size_t kAuthTokenLength = 43;

/** Maximum accepted explicit token byte size. */
constexpr uint32_t kAuthTokenMaxBytes = 64;

/** Random byte count used for one auth challenge. */
constexpr size_t kAuthChallengeBytes = 32;

/** Raw HMAC-SHA-256 auth response byte count. */
constexpr size_t kAuthResponseBytes = 32;

/**
 * Encodes bytes as unpadded RFC 4648 base64url text.
 *
 * @param data Raw bytes to encode.
 * @return Base64url text without padding.
 */
std::string Base64UrlEncode(const std::vector<unsigned char>& data);

/**
 * Generates a new random base64url auth token.
 *
 * @param token Receives the generated token.
 * @param error Receives a human-readable error on failure.
 * @return true on success.
 */
bool GenerateAuthToken(std::string* token, std::string* error);

/**
 * Generates a random authentication challenge.
 *
 * @param challenge Receives the challenge bytes.
 * @param error Receives a human-readable error on failure.
 * @return true on success.
 */
bool GenerateAuthChallenge(
    std::vector<unsigned char>* challenge,
    std::string* error);

/**
 * Creates the expected response for one authentication challenge.
 *
 * @param token Shared token text.
 * @param challenge Challenge bytes sent by the agent.
 * @return Raw HMAC-SHA-256 response bytes.
 */
std::vector<unsigned char> CreateAuthChallengeResponse(
    const std::string& token,
    const std::vector<unsigned char>& challenge);

/**
 * Compares authentication responses without returning early.
 *
 * @param actual Response supplied by the client.
 * @param expected Expected response generated by the agent.
 * @return true when both response byte sequences match exactly.
 */
bool AuthResponseEquals(
    const std::vector<unsigned char>& actual,
    const std::vector<unsigned char>& expected);

}  // namespace agent_rover

#endif  // AGENT_ROVER_WINDOWS_AGENT_AUTH_H
