// agent-rover - A multi-platform TypeScript test driver for GUI applications
// Copyright (c) Kouji Matsui. (@kekyo@mi.kekyo.net)
// Under MIT.
// https://github.com/kekyo/agent-rover

import { CommanderError, createCommand } from 'commander';

import type {
  ConnectRemoteAgentOptions,
  RemoteApplicationLaunchOptions,
} from '../index';

/** Validated operation selected by the CLI. */
export type ArctlOperation =
  | { /** Enumerate windows. */ readonly command: 'windows' }
  | {
      /** Launch an independently owned application. */ readonly command: 'launch';
      /** Remote executable and its launch settings. */ readonly options: RemoteApplicationLaunchOptions;
    }
  | {
      /** Transfer direction. */ readonly command: 'put' | 'get';
      /** Exact source path. */ readonly source: string;
      /** Exact destination path. */ readonly destination: string;
      /** Copy the source directory's contents. */ readonly recursive: boolean;
    }
  | {
      /** Capture a PNG. */ readonly command: 'screenshot';
      /** Local output path. */ readonly output: string;
      /** Exact window ID, or the whole virtual desktop. */ readonly window:
        string | undefined;
    };

/** Parsed invocation of the standalone CLI. */
export type ArctlArguments =
  | {
      /** Local help or version output. */ readonly action: 'display';
      /** Text generated by Commander. */ readonly text: string;
    }
  | ({
      /** Execute a remote operation. */
      readonly action: 'execute';
      /** Resolved connection settings for the operation. */
      readonly connection: ConnectRemoteAgentOptions;
      /** Whether to print one JSON result. */
      readonly json: boolean;
    } & ArctlOperation);

interface ConnectionArguments {
  readonly host: string | undefined;
  readonly port: string | undefined;
  readonly token: string | undefined;
  readonly timeout: string | undefined;
  readonly json: boolean | undefined;
}

interface LaunchArguments {
  readonly cwd: string | undefined;
  readonly env: readonly string[];
  readonly stdout: string | undefined;
  readonly stderr: string | undefined;
}

/**
 * Parses and validates an invocation without opening a connection.
 * @param args Arguments excluding the Node executable and script name.
 * @param environment Environment used for connection defaults.
 * @param version Package version generated by screw-up.
 * @returns A local display action or a validated remote operation.
 */
export const parseArctlArguments = (
  args: readonly string[],
  environment: Readonly<NodeJS.ProcessEnv>,
  version: string
): ArctlArguments => {
  let output = '';
  let operation: ArctlOperation | undefined;
  const program = createCommand('arctl')
    .description('Run one remote operation and leave its results in place.')
    .version(
      `arctl ${version}`,
      '--version',
      'Show the package version without connecting'
    )
    .option('--host <HOST>', 'Agent host (AGENT_ROVER_HOST)')
    .option('--port <PORT>', 'Agent port (AGENT_ROVER_PORT, default 39397)')
    .option('--token <TOKEN>', 'Authentication token (AGENT_ROVER_AUTH_TOKEN)')
    .option(
      '--timeout <SECONDS>',
      'Connection and request timeout (default 30)'
    )
    .option('--json', 'Print one JSON result on stdout')
    .helpOption('-h, --help', 'Show help without connecting')
    .configureHelp({ showGlobalOptions: true })
    .addHelpText(
      'after',
      '\nConnection options may precede or follow the command.\nExit codes: 0 success, 1 operation failure, 2 invalid arguments, 130 interrupted.'
    )
    .configureOutput({
      writeOut: (text) => {
        output += text;
      },
      // The caller reports errors once and redacts authentication tokens.
      writeErr: () => {},
    })
    .exitOverride();
  program
    .command('windows')
    .description(
      'List visible top-level window IDs, PIDs, process names, and titles without activation.'
    )
    .action(() => {
      operation = { command: 'windows' };
    });
  program
    .command('launch')
    .description(
      'Start an application and leave it running after arctl exits. Explicitly launch a shell for shell syntax.'
    )
    .usage('[options] -- <command> [args...]')
    .argument('<command>', 'Remote executable path')
    .argument('[args...]', 'Literal arguments passed to the executable')
    .option('--cwd <DIRECTORY>', 'Remote working directory')
    .option(
      '--env <KEY=VALUE>',
      'Add or replace an environment variable (repeatable)',
      (value: string, previous: string[]) => [...previous, value],
      []
    )
    .option('--stdout <FILE>', 'Remote standard output file')
    .option('--stderr <FILE>', 'Remote standard error file')
    .action((path: string, arguments_: string[], values: LaunchArguments) => {
      const delimiter = args.indexOf('--');
      if (
        delimiter < 0 ||
        args[delimiter + 1] !== path ||
        args.length - delimiter - 2 !== arguments_.length
      )
        throw new Error('launch requires -- before the remote command.');
      for (const [name, value] of [
        ['command', path],
        ['cwd', values.cwd],
        ['stdout', values.stdout],
        ['stderr', values.stderr],
      ]) {
        if (value !== undefined && value.trim() === '')
          throw new Error(`${name} must not be empty.`);
      }
      const environment: Record<string, string> = Object.create(null);
      for (const entry of values.env) {
        const equals = entry.indexOf('=');
        if (equals <= 0)
          throw new Error('--env requires a nonempty KEY followed by =VALUE.');
        environment[entry.slice(0, equals)] = entry.slice(equals + 1);
      }
      operation = {
        command: 'launch',
        options: {
          path,
          arguments: arguments_,
          ...(values.cwd === undefined ? {} : { workingDirectory: values.cwd }),
          ...(values.env.length === 0 ? {} : { environment }),
          ...(values.stdout === undefined ? {} : { stdoutPath: values.stdout }),
          ...(values.stderr === undefined ? {} : { stderrPath: values.stderr }),
        },
      };
    });
  for (const command of ['put', 'get'] as const) {
    program
      .command(command)
      .description(
        `${command === 'put' ? 'Upload local to remote' : 'Download remote to local'}. Specify the exact destination file; existing files are overwritten.`
      )
      .argument('<source>', command === 'put' ? 'Local file' : 'Remote file')
      .argument(
        '<destination>',
        command === 'put' ? 'Remote file' : 'Local file'
      )
      .option(
        '-r, --recursive',
        'Copy directory contents, including empty directories; keep destination-only entries'
      )
      .action(
        (
          source: string,
          destination: string,
          values: { readonly recursive: boolean | undefined }
        ) => {
          if (source.trim() === '' || destination.trim() === '')
            throw new Error('Source and destination must not be empty.');
          operation = {
            command,
            source,
            destination,
            recursive: values.recursive ?? false,
          };
        }
      );
  }
  program
    .command('screenshot')
    .description(
      'Save visible pixels as PNG without activation. Omit --window for the entire virtual desktop. Existing outputs are never overwritten.'
    )
    .argument('<output.png>', 'Local output file')
    .option('--window <ID>', 'Window ID from arctl windows')
    .action(
      (output: string, values: { readonly window: string | undefined }) => {
        if (output.trim() === '') throw new Error('Output must not be empty.');
        if (values.window !== undefined && values.window.trim() === '')
          throw new Error('--window must not be empty.');
        operation = { command: 'screenshot', output, window: values.window };
      }
    );
  try {
    program.parse(args, { from: 'user' });
  } catch (error) {
    if (error instanceof CommanderError && error.exitCode === 0) {
      return { action: 'display', text: output };
    }
    throw error;
  }
  if (operation === undefined)
    throw new Error('A command is required. Use --help.');

  const values = program.opts<ConnectionArguments>();
  const host = values.host ?? environment.AGENT_ROVER_HOST;
  if (host === undefined || host.trim() === '')
    throw new Error('--host or AGENT_ROVER_HOST is required.');
  const portText = values.port ?? environment.AGENT_ROVER_PORT ?? '39397';
  const port = Number(portText);
  if (
    !/^\d+$/u.test(portText) ||
    !Number.isInteger(port) ||
    port < 1 ||
    port > 65535
  ) {
    throw new Error('--port must be an integer from 1 through 65535.');
  }
  const timeoutMs = Number(values.timeout ?? '30') * 1000;
  if (!Number.isFinite(timeoutMs) || timeoutMs < 1 || timeoutMs > 2147483647) {
    throw new Error(
      '--timeout must be positive seconds between 0.001 and 2147483.647.'
    );
  }
  if (values.token !== undefined && values.token.length === 0)
    throw new Error('--token must not be empty.');
  const token = values.token ?? environment.AGENT_ROVER_AUTH_TOKEN;
  return {
    action: 'execute',
    ...operation,
    json: values.json ?? false,
    connection: {
      host,
      port,
      timeoutMs,
      ...(token === undefined || token === '' ? {} : { authToken: token }),
    },
  };
};
