// agent-rover - A multi-platform TypeScript test driver for GUI applications
// Copyright (c) Kouji Matsui. (@kekyo@mi.kekyo.net)
// Under MIT.
// https://github.com/kekyo/agent-rover

import { CommanderError, createCommand } from 'commander';

import type { ConnectRemoteAgentOptions } from '../index';

/** Parsed invocation of the standalone CLI. */
export type ArctlArguments =
  | {
      /** Local help or version output. */ readonly action: 'display';
      /** Text generated by Commander. */ readonly text: string;
    }
  | {
      /** Execute a remote operation. */
      readonly action: 'execute';
      /** Operation to execute. */
      readonly command: 'windows';
      /** Resolved connection settings. */
      readonly connection: ConnectRemoteAgentOptions;
      /** Whether to print one JSON result. */
      readonly json: boolean;
    };

interface ConnectionArguments {
  readonly host: string | undefined;
  readonly port: string | undefined;
  readonly token: string | undefined;
  readonly timeout: string | undefined;
  readonly json: boolean | undefined;
}

/**
 * Parses and validates an invocation without opening a connection.
 * @param args Arguments excluding the Node executable and script name.
 * @param environment Environment used for connection defaults.
 * @param version Package version generated by screw-up.
 * @returns A local display action or a validated remote operation.
 */
export const parseArctlArguments = (
  args: readonly string[],
  environment: Readonly<NodeJS.ProcessEnv>,
  version: string
): ArctlArguments => {
  let output = '';
  let command: 'windows' | undefined;
  const program = createCommand('arctl')
    .description('Run one remote operation and leave its results in place.')
    .version(
      `arctl ${version}`,
      '--version',
      'Show the package version without connecting'
    )
    .option('--host <HOST>', 'Agent host (AGENT_ROVER_HOST)')
    .option('--port <PORT>', 'Agent port (AGENT_ROVER_PORT, default 39397)')
    .option('--token <TOKEN>', 'Authentication token (AGENT_ROVER_AUTH_TOKEN)')
    .option(
      '--timeout <SECONDS>',
      'Connection and request timeout (default 30)'
    )
    .option('--json', 'Print one JSON result on stdout')
    .helpOption('-h, --help', 'Show help without connecting')
    .configureHelp({ showGlobalOptions: true })
    .addHelpText(
      'after',
      '\nConnection options may precede or follow the command.\nExit codes: 0 success, 1 operation failure, 2 invalid arguments, 130 interrupted.'
    )
    .configureOutput({
      writeOut: (text) => {
        output += text;
      },
      // The caller reports errors once and redacts authentication tokens.
      writeErr: () => {},
    })
    .exitOverride();
  program
    .command('windows')
    .description(
      'List visible top-level window IDs, PIDs, process names, and titles without activation.'
    )
    .action(() => {
      command = 'windows';
    });
  try {
    program.parse(args, { from: 'user' });
  } catch (error) {
    if (error instanceof CommanderError && error.exitCode === 0) {
      return { action: 'display', text: output };
    }
    throw error;
  }
  if (command === undefined)
    throw new Error('A command is required. Use --help.');

  const values = program.opts<ConnectionArguments>();
  const host = values.host ?? environment.AGENT_ROVER_HOST;
  if (host === undefined || host.trim() === '')
    throw new Error('--host or AGENT_ROVER_HOST is required.');
  const portText = values.port ?? environment.AGENT_ROVER_PORT ?? '39397';
  const port = Number(portText);
  if (
    !/^\d+$/u.test(portText) ||
    !Number.isInteger(port) ||
    port < 1 ||
    port > 65535
  ) {
    throw new Error('--port must be an integer from 1 through 65535.');
  }
  const timeoutMs = Number(values.timeout ?? '30') * 1000;
  if (!Number.isFinite(timeoutMs) || timeoutMs < 1 || timeoutMs > 2147483647) {
    throw new Error(
      '--timeout must be positive seconds between 0.001 and 2147483.647.'
    );
  }
  if (values.token !== undefined && values.token.length === 0)
    throw new Error('--token must not be empty.');
  const token = values.token ?? environment.AGENT_ROVER_AUTH_TOKEN;
  return {
    action: 'execute',
    command,
    json: values.json ?? false,
    connection: {
      host,
      port,
      timeoutMs,
      ...(token === undefined || token === '' ? {} : { authToken: token }),
    },
  };
};
